name: Build Tweak

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Dependencies, Theos and iOS SDK
        run: |
          brew install ldid
          git clone --recursive https://github.com/theos/theos.git $HOME/theos
          curl -LO https://github.com/theos/sdks/archive/master.zip
          unzip master.zip
          mv sdks-master/* $HOME/theos/sdks/
          rm -r master.zip sdks-master

      - name: Build Package
        run: |
          export THEOS=$HOME/theos
          make package FINALPACKAGE=1

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: BackupTweak-Package
          path: packages/*.deb
